import { Button } from "@/components/ui/button";
import { Shield, Code, Globe, Users } from "lucide-react";

export const HeroSection = () => {
  const scrollToSection = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
  };

  return (
    <section id="home" className="relative min-h-screen flex items-center pt-16 overflow-hidden">
      {/* Terminal Background Animation */}
      <div className="absolute inset-0 bg-cybersec-dark">
        <div className="absolute inset-0 bg-gradient-to-b from-transparent via-cybersec-dark/95 to-cybersec-dark z-10" />
        <pre className="absolute inset-0 text-green-500/20 font-mono text-xs overflow-hidden whitespace-pre p-4">
          <div className="animate-terminal-scroll">
            [    0.000000] Linux version 6.5.0-generic
            [    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-6.5.0-generic
            [    0.000000] x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
            [    0.000000] x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
            [    0.000000] x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
            [    0.000000] x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
            [    0.000000] signal: max sigframe size: 1440
            [    0.000000] BIOS-provided physical RAM map:
            [    0.000000] Secure boot enabled
            [    0.000000] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-6.5.0-generic
            [    0.000000] Initializing cgroup subsys cpuset
            [    0.000000] Initializing cgroup subsys cpu
            [    0.000000] Initializing cgroup subsys cpuacct
            [    0.000000] Linux version 6.5.0-generic
            [    0.000000] Detected 12 CPU cores
            [    0.000000] Memory: 32768MB RAM
            [    0.000000] Initializing network security
            [    0.000000] AppArmor: AppArmor initialized
            [    0.000000] Dentry cache hash table entries: 2097152
            [    0.000000] Inode-cache hash table entries: 1048576
            [    0.000000] Mount-cache hash table entries: 32768
            [    0.000000] CPU: Physical Processor ID: 0
            [    0.000000] mce: CPU supports 10 MCE banks
            [    0.000000] Last level iTLB entries: 4KB 64, 2MB 8, 4MB 8
            [    0.000000] Last level dTLB entries: 4KB 64, 2MB 0, 4MB 0, 1GB 4
            [    0.000000] Spectre V2 : Mitigation: Full generic retpoline
            [    0.000000] Spectre V2 : Spectre v2 / SpectreRSB mitigation: Filling RSB on context switch
            [    0.000000] Speculative Store Bypass: Mitigation: Speculative Store Bypass disabled
            [    0.000000] MDS: Mitigation: Clear CPU buffers
            [    0.000000] Freeing SMP alternatives memory: 40K
            [    0.000000] smpboot: CPU0: Genuine Intel(R) Core(TM) i7-10700K
            [    0.000000] Performance Events: PEBS fmt3+, Skylake events, 32-deep LBR
            [    0.000000] ... version:                4
            [    0.000000] ... bit width:              48
            [    0.000000] ... generic registers:      4
            [    0.000000] ... value mask:             0000ffffffffffff
            [    0.000000] ... max period:             00007fffffffffff
            [    0.000000] ... fixed-purpose events:   3
            [    0.000000] ... event mask:             000000070000000f
            [    0.000000] NMI watchdog: enabled on all CPUs
            [    0.000000] Booting Node 0 Processor 1 APIC 0x2
            [    0.000000] smpboot: CPU1: Genuine Intel(R) Core(TM) i7-10700K
            [    0.000000] Initializing XFRM netlink socket
            [    0.000000] Key type asymmetric registered
            [    0.000000] Asymmetric key parser 'x509' registered
            [    0.000000] Block layer SCSI generic (bsg) driver version 0.4 loaded
            [    0.000000] io scheduler mq-deadline registered
            [    0.000000] io scheduler kyber registered
            [    0.000000] Loading compiled-in X.509 certificates
            [    0.000000] Loaded X.509 cert 'Build time autogenerated kernel key'
            [    0.000000] zswap: loaded using pool lz4/z3fold
            [    0.000000] Key type encrypted registered
            [    0.000000] AppArmor: AppArmor Filesystem Enabled
            [    0.000000] Loading compiled-in module: capability.ko
            [    0.000000] Loading compiled-in module: compat.ko
            [    0.000000] Loading compiled-in module: configfs.ko
            [    0.000000] Loading compiled-in module: kernfs.ko
            [    0.000000] System initialization completed
            [    0.000000] Starting system services...
            [    0.000000] Network interfaces detected
            [    0.000000] Security framework initialized
            [    0.000000] System is now operational
          </div>
        </pre>
      </div>

      <div className="container mx-auto px-4 py-12 relative z-10">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
          <div className="space-y-6">
            <span className="inline-block px-4 py-1.5 bg-primary/10 rounded-full border border-primary/20 text-sm font-medium text-primary">
              Entrepreneur & Ingénieur Système 
            </span>

            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold leading-tight">
              Salut, je suis <span className="tech-gradient">Rudra</span>,<br />
              passionné de Linux & Open Source
            </h1>

            <p className="text-lg text-gray-300 max-w-lg">
              Je conçois des solutions libres, sécurisées et évolutives pour transformer vos défis techniques en réussites durables.
            </p>

            <div className="flex flex-col sm:flex-row gap-4">
              <Button size="lg" className="px-6" onClick={() => scrollToSection('contact')}>
                Contactez-moi
              </Button>
              <Button size="lg" variant="outline" className="px-6" onClick={() => scrollToSection('Projets')}>
                Voir mes projets
              </Button>
            </div>

            <div className="pt-8 grid grid-cols-3 gap-4">
              <div className="text-center">
                <div className="inline-flex items-center justify-center h-12 w-12 rounded-lg bg-primary/20 mb-3">
                  <Shield className="h-6 w-6 text-primary" />
                </div>
                <p className="text-sm">Sécurité & Robustesse</p>
              </div>

              <div className="text-center">
                <div className="inline-flex items-center justify-center h-12 w-12 rounded-lg bg-primary/20 mb-3">
                  <Code className="h-6 w-6 text-primary" />
                </div>
                <p className="text-sm">Passion Open Source</p>
              </div>

              <div className="text-center">
                <div className="inline-flex items-center justify-center h-12 w-12 rounded-lg bg-primary/20 mb-3">
                  <Users className="h-6 w-6 text-primary" />
                </div>
                <p className="text-sm">Esprit Entrepreneurial</p>
              </div>
            </div>
          </div>

          {/* Zone de script inspirant */}
          <div className="relative hidden lg:block">
            <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-80 h-80 bg-primary/30 rounded-full filter blur-3xl" />
            <div className="relative backdrop-blur-sm bg-cybersec-light/10 border border-white/10 rounded-2xl p-8 shadow-lg">
              <pre className="text-xs md:text-sm font-mono text-gray-200 leading-snug">
                <code>
                  <span className="text-blue-400">#!/usr/bin/env bash</span>
                  <br />
                  <span className="text-green-400"># Script: building_better_world.sh</span>
                  <br /><br />
                  <span className="text-yellow-300">function</span> <span className="text-red-400">deploy_hope</span>() {'{'}
                  <br />  <span className="text-purple-400">echo</span> "Deployment of hope..."
                  <br />  <span className="text-gray-400">kubectl apply -f hope_manifest.yaml</span>
                  <br />{'}'}
                  <br />
                  <span className="text-yellow-300">function</span> <span className="text-red-400">scale_impact</span>() {'{'}
                  <br />  <span className="text-purple-400">echo</span> "Scaling positive impact..."
                  <br />  <span className="text-gray-400">helm upgrade impact ./chart --set replicas=infinite</span>
                  <br />{'}'}
                  <br />
                  <span className="text-yellow-300">function</span> <span className="text-red-400">monitor_progress</span>() {'{'}
                  <br />  <span className="text-purple-400">echo</span> "Monitoring progress..."
                  <br />  <span className="text-gray-400">prometheus-cli --query="world_progress"</span>
                  <br />{'}'}
                  <br /><br />
                  <span className="text-green-400"># Exécution</span>
                  <br />deploy_hope
                  <br />scale_impact
                  <br />monitor_progress
                </code>
              </pre>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};